In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
sent=['the glass of milk ','My name is Prateek','Hello how are you','Hello I am fine']

In [13]:
sent

['the glass of milk ',
 'My name is Prateek',
 'Hello how are you',
 'Hello I am fine']

In [14]:
voc_size=100000

In [15]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[67279, 15566, 97516, 82301],
 [99513, 44897, 36049, 61624],
 [74650, 62337, 37182, 95385],
 [74650, 3255, 96739, 16176]]

In [16]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[    0     0     0     0 67279 15566 97516 82301]
 [    0     0     0     0 99513 44897 36049 61624]
 [    0     0     0     0 74650 62337 37182 95385]
 [    0     0     0     0 74650  3255 96739 16176]]


In [19]:
## feature representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-09-15 17:36:55.968428: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2025-09-15 17:36:55.968473: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-09-15 17:36:55.968482: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-09-15 17:36:55.968544: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-09-15 17:36:55.968588: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             1000000   
                                                                 
Total params: 1000000 (3.81 MB)
Trainable params: 1000000 (3.81 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 200ms/step


2025-09-15 17:37:35.705348: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


array([[[-0.0086836 , -0.04578675,  0.04615336, -0.04964111,
         -0.01859312,  0.01196877, -0.04537542,  0.01997818,
         -0.01447358, -0.04041191],
        [-0.0086836 , -0.04578675,  0.04615336, -0.04964111,
         -0.01859312,  0.01196877, -0.04537542,  0.01997818,
         -0.01447358, -0.04041191],
        [-0.0086836 , -0.04578675,  0.04615336, -0.04964111,
         -0.01859312,  0.01196877, -0.04537542,  0.01997818,
         -0.01447358, -0.04041191],
        [-0.0086836 , -0.04578675,  0.04615336, -0.04964111,
         -0.01859312,  0.01196877, -0.04537542,  0.01997818,
         -0.01447358, -0.04041191],
        [ 0.01260697,  0.02997419, -0.0408662 ,  0.03946142,
          0.04410099, -0.02890064, -0.0254787 , -0.0171587 ,
         -0.01096944, -0.03687998],
        [-0.00437931,  0.03233782, -0.04225338, -0.04175981,
          0.0476846 , -0.04935131, -0.00100695, -0.03941942,
         -0.00409506,  0.02224067],
        [ 0.02570316,  0.048053  , -0.00072391, -0.0

In [23]:
embedded_docs[0]

array([    0,     0,     0,     0, 67279, 15566, 97516, 82301],
      dtype=int32)

In [24]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 101ms/step


array([[-0.0086836 , -0.04578675,  0.04615336, -0.04964111, -0.01859312,
         0.01196877, -0.04537542,  0.01997818, -0.01447358, -0.04041191],
       [-0.0086836 , -0.04578675,  0.04615336, -0.04964111, -0.01859312,
         0.01196877, -0.04537542,  0.01997818, -0.01447358, -0.04041191],
       [-0.0086836 , -0.04578675,  0.04615336, -0.04964111, -0.01859312,
         0.01196877, -0.04537542,  0.01997818, -0.01447358, -0.04041191],
       [-0.0086836 , -0.04578675,  0.04615336, -0.04964111, -0.01859312,
         0.01196877, -0.04537542,  0.01997818, -0.01447358, -0.04041191],
       [ 0.01260697,  0.02997419, -0.0408662 ,  0.03946142,  0.04410099,
        -0.02890064, -0.0254787 , -0.0171587 , -0.01096944, -0.03687998],
       [-0.00437931,  0.03233782, -0.04225338, -0.04175981,  0.0476846 ,
        -0.04935131, -0.00100695, -0.03941942, -0.00409506,  0.02224067],
       [ 0.02570316,  0.048053  , -0.00072391, -0.03956924,  0.00989232,
         0.0164717 , -0.04652798,  0.02469189